<?php
/**
 * @package     Sda\Component\Sdajem\Administrator\Model
 * @subpackage
 *
 * @copyright   A copyright
 * @license     A "Slug" license name e.g. GPL2
 */

namespace Sda\Component\Sdajem\Administrator\Model;

use Joomla\CMS\MVC\Model\ListModel;

class UsersModel extends ListModel
{
	public function getListQuery()
	{
		return parent::getListQuery(); // TODO: Change the autogenerated stub
	}
}